Parameters:
  Region:
    Type: String 
    Default: "us-west-2" 

  AccountId:
    Type: String 
    Default: "495679467660"

Resources:
  # Need: API gateway, API gateway method, maybe need API gateway resource, labmda function, dynamodb table

  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties: 
      # ApiKeySourceType: String (will need this eventually)
      Description: "Rest API for our 391 project"
      EndpointConfiguration: 
          Types: 
          - REGIONAL
      Name: "391_API"
      Tags: 
        - 
          Key: "Use_Category"
          Value: "CPEN391"
  apiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: False
      AuthorizationType: NONE
      # AuthorizerId: String
      HttpMethod: POST
      Integration: 
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: 
          Fn::Sub: "arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${Region}:${AccountId}:function:PutResult/invocations"
      OperationName: "PutResult"
      ResourceId: 
        Fn::GetAtt: [apiGateway, RootResourceId]
      RestApiId:
        Ref: apiGateway

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - apiMethod
    Properties:
      RestApiId: 
        Ref: apiGateway
      StageName: "call"

  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: 
        Fn::Sub: arn:aws:lambda:${Region}:${AccountId}:function:PutResult # [lambdaFunction, Arn]
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: "arn:aws:execute-api:${Region}:${AccountId}:${apiGateway}/*/POST/"

  # Type: AWS::Lambda::Function
  # Properties: 
  #   Code: 
  #     Code
  #   DeadLetterConfig: 
  #     DeadLetterConfig
  #   Description: String
  #   Environment: 
  #     Environment
  #   FunctionName: String
  #   Handler: String
  #   KmsKeyArn: String
  #   Layers: 
  #     - String
  #   MemorySize: Integer
  #   ReservedConcurrentExecutions: Integer
  #   Role: String
  #   Runtime: String
  #   Tags: 
  #     - 
  #       Key: "Use_Category"
  #       Value: "CPEN391"
  #   Timeout: Integer
  #   TracingConfig: 
  #     TracingConfig
  #   VpcConfig: 
  #     VpcConfig

  # Type: AWS::DynamoDB::Table
  # Properties: 
  #   AttributeDefinitions: 
  #     - AttributeDefinition
  #   BillingMode: String
  #   GlobalSecondaryIndexes: 
  #     - GlobalSecondaryIndex
  #   KeySchema: 
  #     - KeySchema
  #   LocalSecondaryIndexes: 
  #     - LocalSecondaryIndex
  #   PointInTimeRecoverySpecification: 
  #     PointInTimeRecoverySpecification
  #   ProvisionedThroughput: 
  #     ProvisionedThroughput
  #   SSESpecification: 
  #     SSESpecification
  #   StreamSpecification: 
  #     StreamSpecification
  #   TableName: String
  #   Tags: 
  #     - 
  #       Key: "Use_Category"
  #       Value: "CPEN391"
  #   TimeToLiveSpecification: 
  #     TimeToLiveSpecification
